### ISSUE TITLE
buildout failed

### ISSUE THREAD

**Issue by juh2** [veit/vs_buildout#2]
Ich bekomme einen Fehler beim Aufruf von python bootstrap

juh@sokrates:~/Downloads/plone5$ python2.7 bootstrap.py -c devel.cfg
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-18.0.1.zip
Extracting in /tmp/tmpxwccD3
Now working in /tmp/tmpxwccD3/setuptools-18.0.1
Building a Setuptools egg in /tmp/tmpKox7tm
/tmp/tmpKox7tm/setuptools-18.0.1-py2.7.egg
/tmp/tmpKox7tm/setuptools-18.0.1-py2.7.egg/pkg_resources/**init**.py:203: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
While:
  Initializing.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/tmp/tmpKox7tm/zc.buildout-2.4.0-py2.7.egg/zc/buildout/buildout.py", line 1986, in main
    user_defaults, command, args)
  File "/tmp/tmpKox7tm/zc.buildout-2.4.0-py2.7.egg/zc/buildout/buildout.py", line 231, in **init**
    data['buildout'].copy(), override, set()))
  File "/tmp/tmpKox7tm/zc.buildout-2.4.0-py2.7.egg/zc/buildout/buildout.py", line 1621, in _open
    downloaded)
  File "/tmp/tmpKox7tm/zc.buildout-2.4.0-py2.7.egg/zc/buildout/buildout.py", line 1621, in _open
    downloaded)
  File "/tmp/tmpKox7tm/zc.buildout-2.4.0-py2.7.egg/zc/buildout/buildout.py", line 1601, in _open
    result = zc.buildout.configparser.parse(fp, filename, _default_globals)
  File "/tmp/tmpKox7tm/zc.buildout-2.4.0-py2.7.egg/zc/buildout/configparser.py", line 234, in parse
    raise e
ParsingError: File contains parsing errors: /home/juh/Downloads/plone5/plone-versions.cfg
    [line 29]: '<<<<<<< HEAD\n'
    [line 35]: '=======\n'
    [line 41]: '>>>>>>> 5b16318407bdf9c53e54f4497631517a4dfef291\n'
    [line 53]: '<<<<<<< HEAD\n'
    [line 56]: '=======\n'
    [line 59]: '>>>>>>> 5b16318407bdf9c53e54f4497631517a4dfef291\n'
    [line 101]: '<<<<<<< HEAD\n'
    [line 115]: '=======\n'
    [line 130]: '>>>>>>> 5b16318407bdf9c53e54f4497631517a4dfef291\n'
    [line 137]: '<<<<<<< HEAD\n'
    [line 147]: '=======\n'
    [line 157]: '>>>>>>> 5b16318407bdf9c53e54f4497631517a4dfef291\n'
    [line 165]: '<<<<<<< HEAD\n'
    [line 167]: '=======\n'
    [line 169]: '>>>>>>> 5b16318407bdf9c53e54f4497631517a4dfef291\n'
    [line 180]: '<<<<<<< HEAD\n'
    [line 227]: '=======\n'
    [line 277]: '>>>>>>> 5b16318407bdf9c53e54f4497631517a4dfef291\n'
    [line 282]: '<<<<<<< HEAD\n'
    [line 290]: '=======\n'
    [line 298]: '>>>>>>> 5b16318407bdf9c53e54f4497631517a4dfef291\n'
    [line 303]: '<<<<<<< HEAD\n'
    [line 309]: '=======\n'
    [line 315]: '>>>>>>> 5b16318407bdf9c53e54f4497631517a4dfef291\n'
    [line 323]: '<<<<<<< HEAD\n'
    [line 326]: '=======\n'
    [line 329]: '>>>>>>> 5b16318407bdf9c53e54f4497631517a4dfef291\n'
    [line 335]: '<<<<<<< HEAD\n'
    [line 341]: '=======\n'
    [line 347]: '>>>>>>> 5b16318407bdf9c53e54f4497631517a4dfef291\n'
    [line 355]: '<<<<<<< HEAD\n'
    [line 362]: '=======\n'
    [line 369]: '>>>>>>> 5b16318407bdf9c53e54f4497631517a4dfef291\n'
    [line 392]: '<<<<<<< HEAD\n'
    [line 400]: '=======\n'
    [line 408]: '>>>>>>> 5b16318407bdf9c53e54f4497631517a4dfef291\n'
    [line 415]: '<<<<<<< HEAD\n'
    [line 423]: '=======\n'
    [line 426]: '>>>>>>> 5b16318407bdf9c53e54f4497631517a4dfef291\n'

**Comment by veit** [comment]
Hallo Juh,
vielen Dank für den Hinweis. Ich hatte versehentlich einen Merge-Konflikt nicht richtig aufgelöst. Der Fehler ist nun behoben. Nachdem Du die plone-versions.cfg aktualisiert hast, sollte nun alles problemlos laufen.

**Comment by juh2** [comment]
Hallo Veit,

merci.

Jetzt hängt es aber hier:

Bei
./bin/buildout -c devel.cfg

```
While:
  Installing instance.
  Getting distribution for 'Products.PluggableAuthService==1.10.0'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/juh/Downloads/plone5/eggs/zc.buildout-2.4.0-py2.7.egg/zc/buildout/    buildout.py", line 1987, in main
    getattr(buildout, command)(args)
  File "/home/juh/Downloads/plone5/eggs/zc.buildout-2.4.0-py2.7.egg/zc/buildout/    buildout.py", line 668, in install
    installed_files = self[part]._call(recipe.install)
  File "/home/juh/Downloads/plone5/eggs/zc.buildout-2.4.0-py2.7.egg/zc/buildout/    buildout.py", line 1409, in _call
    return f()
  File "/home/juh/Downloads/plone5/eggs/plone.recipe.zope2instance-4.2.17-py2.7.    egg/plone/recipe/zope2instance/__init__.py", line 113, in install
    installed.extend(self.install_scripts())
  File "/home/juh/Downloads/plone5/eggs/plone.recipe.zope2instance-4.2.17-py2.7.    egg/plone/recipe/zope2instance/__init__.py", line 601, in install_scripts
    requirements, ws = self.egg.working_set(['plone.recipe.zope2instance'])
  File "/home/juh/Downloads/plone5/eggs/zc.recipe.egg-1.3.2-py2.7.egg/zc/recipe/    egg/egg.py", line 101, in working_set
    **kw)
  File "/home/juh/Downloads/plone5/eggs/zc.buildout-2.4.0-py2.7.egg/zc/buildout/    easy_install.py", line 848, in install
    return installer.install(specs, working_set)
  File "/home/juh/Downloads/plone5/eggs/zc.buildout-2.4.0-py2.7.egg/zc/buildout/    easy_install.py", line 685, in install
    for_buildout_run=for_buildout_run):
  File "/home/juh/Downloads/plone5/eggs/zc.buildout-2.4.0-py2.7.egg/zc/buildout/    easy_install.py", line 477, in _get_dist
    dist, avail = self._satisfied(requirement)
  File "/home/juh/Downloads/plone5/eggs/zc.buildout-2.4.0-py2.7.egg/zc/buildout/    easy_install.py", line 234, in _satisfied
    return None, self._obtain(req, source)
  File "/home/juh/Downloads/plone5/eggs/zc.buildout-2.4.0-py2.7.egg/zc/buildout/    easy_install.py", line 402, in _obtain
    if index.obtain(requirement) is None:
  File "build/bdist.linux-x86_64/egg/setuptools/package_index.py", line 443, in     obtain
    self.find_packages(requirement)
  File "build/bdist.linux-x86_64/egg/setuptools/package_index.py", line 427, in     find_packages
    self.scan_url(self.index_url + requirement.unsafe_name+'/')
  File "build/bdist.linux-x86_64/egg/setuptools/package_index.py", line 761, in     scan_url
    self.process_url(url, True)
  File "build/bdist.linux-x86_64/egg/setuptools/package_index.py", line 304, in     process_url
    f = self.open_url(url, "Download error on %s: %%s -- Some packages may not be     found!" % url)
  File "/home/juh/Downloads/plone5/eggs/jarn.setuptoolsfixer-1.0-py2.7.egg/jarn/    setuptoolsfixer/__init__.py", line 11, in open_url
    return _old_open_url(self, url, warning=warning)
  File "build/bdist.linux-x86_64/egg/setuptools/package_index.py", line 700, in     open_url
    return open_with_auth(url, self.opener)
  File "build/bdist.linux-x86_64/egg/setuptools/package_index.py", line 894, in     _socket_timeout
    return func(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/setuptools/package_index.py", line 1007, in     open_with_auth
    fp = opener(request)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
```

**Comment by veit** [comment]
Hallo Juh,

"Connection reset by peer" bedeutet, dass der Server auf die  TCP/IP-Anfrage nicht antwortet. Dies lässt auf ein Problem auf einem der Server schließen. Hier lässt sich von Deiner Seite nicht wirklich etwas ändern. Bestenfalls kannst Du das Buildout-Skript erneut aufrufen in der Hoffnung, dass der entsprechende Server dann antwortet.

**Comment by juh2** [comment]
Ah ok. Den Verdacht hatte ich auch. Kann ich irgendwie herausfinden, welcher Server das ist? Das sollte ja eigentlich nicht passieren.

**Comment by veit** [comment]
Hallo Juh,
in diesem Fall konnte Products.PluggableAuthService 1.10.0 nicht heruntergeladen werden. Der Standardwert von  Buildout ist der Python Package Index PyPI, genau http://pypi.python.org/simple/. Es lassen sich jedoch andere Distributionen angeben wenn im `[buildout]`-Abschnitt in `index` entsprechende URLs angegeben werden. 
Üblicherweise werden die Pakete wie bei einem Spider durchsucht. Sollen die Hosts eingeschränkt werden, kann dies mit `allow-hosts` geschehen. 
Den nicht-antwortenden Host bekommst Du jedoch vmtl. bestenfalls heraus, wenn Du Buildout entsprechend verbose aufrufst.
